//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langresources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langresources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.langresources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKSAR Social Enterprise.
        /// </summary>
        internal static string p1_l1 {
            get {
                return ResourceManager.GetString("p1_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong Social Enterprise Incubation Centre Ltd..
        /// </summary>
        internal static string p1_l10 {
            get {
                return ResourceManager.GetString("p1_l10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKSEC.
        /// </summary>
        internal static string p1_l2 {
            get {
                return ResourceManager.GetString("p1_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKCSS-HSBC Social Enterprise Business Centre.
        /// </summary>
        internal static string p1_l3 {
            get {
                return ResourceManager.GetString("p1_l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Enterprise Directory 2013.
        /// </summary>
        internal static string p1_l4 {
            get {
                return ResourceManager.GetString("p1_l4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Enterprise Summit.
        /// </summary>
        internal static string p1_l5 {
            get {
                return ResourceManager.GetString("p1_l5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong Social Entrepreneurship Forum.
        /// </summary>
        internal static string p1_l6 {
            get {
                return ResourceManager.GetString("p1_l6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong General Chamber of Social Enterprises Limited.
        /// </summary>
        internal static string p1_l7 {
            get {
                return ResourceManager.GetString("p1_l7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ET.Net Social Enterprise Gallery社企廊.
        /// </summary>
        internal static string p1_l8 {
            get {
                return ResourceManager.GetString("p1_l8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Ventures Hong Kong.
        /// </summary>
        internal static string p1_l9 {
            get {
                return ResourceManager.GetString("p1_l9", resourceCulture);
            }
        }
    }
}
