//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langaboutus {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langaboutus() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.langaboutus", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s globalized world has further brought to light the complexity of many problems the world is facing that cannot be resolved by the lone efforts of any one sector or discipline. Recognition of the cross-sectorial nature of these problems has led to increasing calls to find holistic, long term solutions. There has been a growing global wave of SOCIAL ENTREPRENEURSHIP where individuals and institutions with broader social agenda have started to tackle these problems by going beyond the systemic norm with [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p1_1 {
            get {
                return ResourceManager.GetString("p1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROJECT FLAME harnesses the values of the City University of Hong Kong to an energetic program of social entrepreneurial education and praxis. On the one hand, it is committed to excellence in professional education and research. On the other, it is committed to the pursuit of equitable and sustainable solutions to local and global institutional failures through social innovation and student leadership development..
        /// </summary>
        internal static string p1_2 {
            get {
                return ResourceManager.GetString("p1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadly, the Mission of Project Flame is:.
        /// </summary>
        internal static string p2_h1 {
            get {
                return ResourceManager.GetString("p2_h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To foster social innovation, impact and transformation through education, innovation incubation, research and knowledge transfer, and student service leadership through proactive collaboration with diverse local and international partners, spanning civil society, business, industry, academic and government;.
        /// </summary>
        internal static string p2_l1 {
            get {
                return ResourceManager.GetString("p2_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To become the leading tertiary sector center in Hong Kong, China and Asia for the advancement of knowledge transfer and practice in social innovation and entrepreneurship..
        /// </summary>
        internal static string p2_l2 {
            get {
                return ResourceManager.GetString("p2_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In September 2011, several staff who shared the belief that social innovation and social entrepreneurship (SE) activities can and should be developed as a core platform for education, research, student learning, and community engagement at CityU formed a study group on their own initiative. Interdisciplinary interest spread rapidly until faculty from 17 different departments/ units - including staff from Public and Social Administration (PSA), Asian and International Studies, Applied Social Studies, Economi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p3_1 {
            get {
                return ResourceManager.GetString("p3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the group gained strength, contacts with local and international social entrepreneurs and with academics in this field confirmed that such an initiative could add considerable value and meaning to the discovery-enriched education and life-long learning of CityU&apos;s students. Coming from non-privileged backgrounds and often the first generation in their family to receive tertiary education, our students have the most to gain and contribute from opportunities to develop positive mindsets and skills in social [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p3_2 {
            get {
                return ResourceManager.GetString("p3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further, the self-initiated and truly multidisciplinary nature of the group gives us competitive advantage over single-disciplined based initiatives elsewhere. In particular, the cross-fertilization of disciplines and experiences give us an unusually strong foundation on which to build important contributions to innovation incubation and to research and knowledge transfer. Above all, we see that the project can make a major contribution to the creation of social value and impact within the various local, ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string p3_3 {
            get {
                return ResourceManager.GetString("p3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognizing the group&apos;s vision, commitment and energy, the university granted permission for us to commence start-up operations in July 2012. We are now established under the interim title of &apos;Project Flame: Social Innovation and Entrepreneurship at CityU&apos; (SIE@CityU)..
        /// </summary>
        internal static string p3_4 {
            get {
                return ResourceManager.GetString("p3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string p4 {
            get {
                return ResourceManager.GetString("p4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        internal static string p5_1 {
            get {
                return ResourceManager.GetString("p5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3A, Block 1, To Yuen Building, To Yuen Street, Kowloon, Hong Kong..
        /// </summary>
        internal static string p5_1c {
            get {
                return ResourceManager.GetString("p5_1c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        internal static string p5_2 {
            get {
                return ResourceManager.GetString("p5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        internal static string p5_3 {
            get {
                return ResourceManager.GetString("p5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string p5_4 {
            get {
                return ResourceManager.GetString("p5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Hour:.
        /// </summary>
        internal static string p5_5 {
            get {
                return ResourceManager.GetString("p5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon-Fri:&lt;br&gt;  9:00 am-6:00 pm&lt;br&gt;  (Lunch Break: 12:30 pm-2:00 pm).
        /// </summary>
        internal static string p5_5c {
            get {
                return ResourceManager.GetString("p5_5c", resourceCulture);
            }
        }
    }
}
