//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class langvalues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal langvalues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.langvalues", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2012-13: Gateway Education (GE) courses:&lt;br&gt;
        ///            Student placements and internships.
        /// </summary>
        internal static string p1_l1 {
            get {
                return ResourceManager.GetString("p1_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longer term plans include:.
        /// </summary>
        internal static string p1_l2 {
            get {
                return ResourceManager.GetString("p1_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interdisciplinary Minor in Social Entrepreneurship.
        /// </summary>
        internal static string p1_l2_l1 {
            get {
                return ResourceManager.GetString("p1_l2_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developing a Major and also a self-financing MA or M.Soc.Sci in Social Innovation and Entrepreneurship.
        /// </summary>
        internal static string p1_l2_l2 {
            get {
                return ResourceManager.GetString("p1_l2_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-financing entrepreneurial / innovation skill development programmes for practitioners to enhance and share their knowledge, competencies and insights..
        /// </summary>
        internal static string p1_l2_l3 {
            get {
                return ResourceManager.GetString("p1_l2_l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Service Leadership Development (SSLD) education shares common values and contents with the education that underpins social innovation and entrepreneurship..
        /// </summary>
        internal static string p2_1 {
            get {
                return ResourceManager.GetString("p2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE courses: to deliver the core knowledge, skills, and values that buttress SSLD. These will include the specially tailored flagship course on Enhancing Your Service Leadership for the 21st Century. .  The GE courses: Get Mad! (Make a Difference): the Challenge to Social Entrepreneurs; and Critical and Cultural Issues in Hong Kong&apos;s Service Economy will also contribute to SSLD education..
        /// </summary>
        internal static string p2_l1 {
            get {
                return ResourceManager.GetString("p2_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Internships: in Government, Business, Third Sector, and Socially Entrepreneurial Organizations that will enable students both to learn from and contribute to the organizations involved..
        /// </summary>
        internal static string p2_l2 {
            get {
                return ResourceManager.GetString("p2_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Entrepreneurship Experience:  students will be coached by faculty and community experts to enter competitions for social entrepreneurship, e.g. the Social Enterprise Challenge open to all university students in Hong Kong..
        /// </summary>
        internal static string p2_l3 {
            get {
                return ResourceManager.GetString("p2_l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands-on experience in implementing social enterprises tutored by faculty and practitioners..
        /// </summary>
        internal static string p2_l4 {
            get {
                return ResourceManager.GetString("p2_l4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Fellowships: for Advanced Students to participate in overseas courses and study tours, sharing their learning with peers on their return to Hong Kong (funding permitting)..
        /// </summary>
        internal static string p2_l5 {
            get {
                return ResourceManager.GetString("p2_l5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Innovation and Entrepreneurship are among the fastest growing areas of research across the social sciences and business management fields. Project Flame aspires to be a leader in regional and international SE / Innovation research and knowledge transfer..
        /// </summary>
        internal static string p3_1 {
            get {
                return ResourceManager.GetString("p3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-disciplinary, local and international collaborative research on SE in Hong Kong and in worldwide.
        /// </summary>
        internal static string p3_l1 {
            get {
                return ResourceManager.GetString("p3_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major research themes could be drawn from  key areas such as:&lt;br/&gt;.
        /// </summary>
        internal static string p3_l2 {
            get {
                return ResourceManager.GetString("p3_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping the range and scope of local and regional SEs;.
        /// </summary>
        internal static string p3_l2_l1 {
            get {
                return ResourceManager.GetString("p3_l2_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financing and resourcing means and models including self-generated revenue, start-up and other grants,  micro-financing,  venture philanthropy, impact investment, capital funds and social enterprise stock exchanges;.
        /// </summary>
        internal static string p3_l2_l10 {
            get {
                return ResourceManager.GetString("p3_l2_l10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public policies, regulations and tax-regimes for social innovation and enterprise;.
        /// </summary>
        internal static string p3_l2_l11 {
            get {
                return ResourceManager.GetString("p3_l2_l11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE sustainability and life-cycles from start-up, to growth, scaling-up, or to demise;.
        /// </summary>
        internal static string p3_l2_l12 {
            get {
                return ResourceManager.GetString("p3_l2_l12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE market research, product design production, marketing;.
        /// </summary>
        internal static string p3_l2_l13 {
            get {
                return ResourceManager.GetString("p3_l2_l13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE business and human resources management;.
        /// </summary>
        internal static string p3_l2_l14 {
            get {
                return ResourceManager.GetString("p3_l2_l14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE social impact evaluation metrics, performance measurement;.
        /// </summary>
        internal static string p3_l2_l15 {
            get {
                return ResourceManager.GetString("p3_l2_l15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scaling-up strategies for SEs including international branching, partnering, social franchising, transnational impact investment, etc..
        /// </summary>
        internal static string p3_l2_l16 {
            get {
                return ResourceManager.GetString("p3_l2_l16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sectoral studies - eg. social innovation and enterprise for resolving ageing and health care problems..
        /// </summary>
        internal static string p3_l2_l17 {
            get {
                return ResourceManager.GetString("p3_l2_l17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical factors in social innovation and creativity;.
        /// </summary>
        internal static string p3_l2_l2 {
            get {
                return ResourceManager.GetString("p3_l2_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical factors in achieving SE success or failure;.
        /// </summary>
        internal static string p3_l2_l3 {
            get {
                return ResourceManager.GetString("p3_l2_l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategies for harnessing  new and existing technologies;.
        /// </summary>
        internal static string p3_l2_l4 {
            get {
                return ResourceManager.GetString("p3_l2_l4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developing entrepreneurial solutions to social problems;.
        /// </summary>
        internal static string p3_l2_l5 {
            get {
                return ResourceManager.GetString("p3_l2_l5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social goods and social value creation;.
        /// </summary>
        internal static string p3_l2_l6 {
            get {
                return ResourceManager.GetString("p3_l2_l6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incubators for innovations in managing social and ecological challenges;.
        /// </summary>
        internal static string p3_l2_l7 {
            get {
                return ResourceManager.GetString("p3_l2_l7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application of &apos;frugal technology&apos; and new media to social problems;.
        /// </summary>
        internal static string p3_l2_l8 {
            get {
                return ResourceManager.GetString("p3_l2_l8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross-sectoral and stakeholder interactions;.
        /// </summary>
        internal static string p3_l2_l9 {
            get {
                return ResourceManager.GetString("p3_l2_l9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular seminar series by scholars and practitioners.
        /// </summary>
        internal static string p3_l3 {
            get {
                return ResourceManager.GetString("p3_l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International workshop.
        /// </summary>
        internal static string p3_l4 {
            get {
                return ResourceManager.GetString("p3_l4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual large-scale on-campus forum or fair.
        /// </summary>
        internal static string p3_l5 {
            get {
                return ResourceManager.GetString("p3_l5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications and dissemination programme.
        /// </summary>
        internal static string p3_l6 {
            get {
                return ResourceManager.GetString("p3_l6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active participation in local and international conferences and networks.
        /// </summary>
        internal static string p3_l7 {
            get {
                return ResourceManager.GetString("p3_l7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Flame will function as a community-centred Collaborative Hub for the incubation and support of social innovation and entrepreneurship, providing a space for the exchange of innovative ideas, practices, and social interventions..
        /// </summary>
        internal static string p4_1 {
            get {
                return ResourceManager.GetString("p4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learning Commons: a physical, intellectual, and human resource hub and reference centre for faculty, students and community organizations to come together to share and access information, brainstorm ideas, exchange practice insights, and work on collaborative projects..
        /// </summary>
        internal static string p4_l1 {
            get {
                return ResourceManager.GetString("p4_l1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Social Entrepreneurs in Residence&quot;:  outside experts spending time in CityU to share experiences, conduct research, organize master classes for agency heads and practitioners, hold seminars and workshops, and spearhead town-and-gown exchanges and international collaboration..
        /// </summary>
        internal static string p4_l2 {
            get {
                return ResourceManager.GetString("p4_l2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case Bank on Social Entrepreneurship: inter-disciplinary teams of staff/ students / practitioners preparing case studies/reports, journal articles, and books and in various formats - print, slides, video or film. The aim is to build up a bank on best local and international practice for use in teaching, research, and idea incubation..
        /// </summary>
        internal static string p4_l3 {
            get {
                return ResourceManager.GetString("p4_l3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff development and networking: proactively seeking new learning opportunities and developing local and international networks and partnerships to ensure we keep abreast of innovation and current practices in social entrepreneurship and service leadership..
        /// </summary>
        internal static string p4_l4 {
            get {
                return ResourceManager.GetString("p4_l4", resourceCulture);
            }
        }
    }
}
