//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;A Place for Hidden Treasure&quot;.
        /// </summary>
        internal static string apfht {
            get {
                return ResourceManager.GetString("apfht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string changeLang {
            get {
                return ResourceManager.GetString("changeLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Sedan Competition.
        /// </summary>
        internal static string diamondsedan {
            get {
                return ResourceManager.GetString("diamondsedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your E-mail address.
        /// </summary>
        internal static string enteremail {
            get {
                return ResourceManager.GetString("enteremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Hand&amp;#178; Spot.
        /// </summary>
        internal static string enterH2S {
            get {
                return ResourceManager.GetString("enterH2S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sure?.
        /// </summary>
        internal static string issure {
            get {
                return ResourceManager.GetString("issure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Know more about us.
        /// </summary>
        internal static string knowmore {
            get {
                return ResourceManager.GetString("knowmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string nav1 {
            get {
                return ResourceManager.GetString("nav1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minor.
        /// </summary>
        internal static string nav10 {
            get {
                return ResourceManager.GetString("nav10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        internal static string nav2 {
            get {
                return ResourceManager.GetString("nav2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        internal static string nav2_2 {
            get {
                return ResourceManager.GetString("nav2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string nav2_3 {
            get {
                return ResourceManager.GetString("nav2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Team.
        /// </summary>
        internal static string nav2_4 {
            get {
                return ResourceManager.GetString("nav2_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string nav2_5 {
            get {
                return ResourceManager.GetString("nav2_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values.
        /// </summary>
        internal static string nav3 {
            get {
                return ResourceManager.GetString("nav3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VALUES.
        /// </summary>
        internal static string nav3Cap {
            get {
                return ResourceManager.GetString("nav3Cap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic and Professional Education.
        /// </summary>
        internal static string nav3_1 {
            get {
                return ResourceManager.GetString("nav3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Service Leadership.
        /// </summary>
        internal static string nav3_2 {
            get {
                return ResourceManager.GetString("nav3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research and Knowledge Transfer.
        /// </summary>
        internal static string nav3_3 {
            get {
                return ResourceManager.GetString("nav3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Innovation Incubation.
        /// </summary>
        internal static string nav3_4 {
            get {
                return ResourceManager.GetString("nav3_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        internal static string nav4 {
            get {
                return ResourceManager.GetString("nav4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Enterprise Visit.
        /// </summary>
        internal static string nav4_1 {
            get {
                return ResourceManager.GetString("nav4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TMCA Tung Chung Green Organic Farm Visit.
        /// </summary>
        internal static string nav4_1_1 {
            get {
                return ResourceManager.GetString("nav4_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit &quot;Dialogue in the Dark&quot;.
        /// </summary>
        internal static string nav4_1_2 {
            get {
                return ResourceManager.GetString("nav4_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Ceremony of &quot;Hand2 Spot&quot; cum &quot;Photo with a Message&quot;&lt;br&gt; Photo Contest Awarding Ceremony.
        /// </summary>
        internal static string nav4_1_4 {
            get {
                return ResourceManager.GetString("nav4_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Enterprise Study Trip in Singapore.
        /// </summary>
        internal static string nav4_1_5 {
            get {
                return ResourceManager.GetString("nav4_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seminars.
        /// </summary>
        internal static string nav4_2 {
            get {
                return ResourceManager.GetString("nav4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Enterpreneur in Resident.
        /// </summary>
        internal static string nav4_2_1 {
            get {
                return ResourceManager.GetString("nav4_2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Enterprise and the Community.
        /// </summary>
        internal static string nav4_2_2 {
            get {
                return ResourceManager.GetString("nav4_2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogue with Enterprise Operators-Bosco Ng, WEDO Global.
        /// </summary>
        internal static string nav4_2_3 {
            get {
                return ResourceManager.GetString("nav4_2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string nav4_3 {
            get {
                return ResourceManager.GetString("nav4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond Sedan Competition 2012.
        /// </summary>
        internal static string nav4_3_1 {
            get {
                return ResourceManager.GetString("nav4_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CityU in Social Enterprise Summit.
        /// </summary>
        internal static string nav4_3_2 {
            get {
                return ResourceManager.GetString("nav4_3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity Building.
        /// </summary>
        internal static string nav4_4 {
            get {
                return ResourceManager.GetString("nav4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photograph Capacity Building Workshop.
        /// </summary>
        internal static string nav4_4_1 {
            get {
                return ResourceManager.GetString("nav4_4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Photo with a Message&quot; Photo Contest.
        /// </summary>
        internal static string nav4_4_2 {
            get {
                return ResourceManager.GetString("nav4_4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Enterprise New Year Festival.
        /// </summary>
        internal static string nav4_5 {
            get {
                return ResourceManager.GetString("nav4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Screening.
        /// </summary>
        internal static string nav4_6 {
            get {
                return ResourceManager.GetString("nav4_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sevice Leadership.
        /// </summary>
        internal static string nav4_7 {
            get {
                return ResourceManager.GetString("nav4_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KMB Headquater Visit.
        /// </summary>
        internal static string nav4_7_1 {
            get {
                return ResourceManager.GetString("nav4_7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLP Customer Service Centre Visit.
        /// </summary>
        internal static string nav4_7_2 {
            get {
                return ResourceManager.GetString("nav4_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internship.
        /// </summary>
        internal static string nav4_8 {
            get {
                return ResourceManager.GetString("nav4_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zhongshan Social Enterprise Internship.
        /// </summary>
        internal static string nav4_8_1 {
            get {
                return ResourceManager.GetString("nav4_8_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE Courses.
        /// </summary>
        internal static string nav5 {
            get {
                return ResourceManager.GetString("nav5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE1218&lt;br&gt;&lt;small&gt;-Make a Difference: The Challenge of Social Entrepreneurs in a Globalized World&lt;/small&gt;.
        /// </summary>
        internal static string nav5_1 {
            get {
                return ResourceManager.GetString("nav5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GE1220&lt;br&gt;&lt;small&gt;-Enhancing Your Service Leadership for the 21st Century&lt;/small&gt;.
        /// </summary>
        internal static string nav5_2 {
            get {
                return ResourceManager.GetString("nav5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos and Video.
        /// </summary>
        internal static string nav5_3 {
            get {
                return ResourceManager.GetString("nav5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources.
        /// </summary>
        internal static string nav6 {
            get {
                return ResourceManager.GetString("nav6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful Websites.
        /// </summary>
        internal static string nav6_1 {
            get {
                return ResourceManager.GetString("nav6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string nav6_2 {
            get {
                return ResourceManager.GetString("nav6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand&amp;#178; Spot.
        /// </summary>
        internal static string nav7 {
            get {
                return ResourceManager.GetString("nav7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events.
        /// </summary>
        internal static string nav8 {
            get {
                return ResourceManager.GetString("nav8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Leadership.
        /// </summary>
        internal static string nav9 {
            get {
                return ResourceManager.GetString("nav9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string navB {
            get {
                return ResourceManager.GetString("navB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor in SE.
        /// </summary>
        internal static string nav_SE {
            get {
                return ResourceManager.GetString("nav_SE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project FLAME.
        /// </summary>
        internal static string pf {
            get {
                return ResourceManager.GetString("pf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.google.com/spreadsheet/pub?key=0AqxsDqWkRWnsdE9sRzdiRWVzTEhlc1p1ak40WGFjUXc&amp;output=html.
        /// </summary>
        internal static string Programs_link {
            get {
                return ResourceManager.GetString("Programs_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Innovation &amp; Entrepreneurship.
        /// </summary>
        internal static string Socialie {
            get {
                return ResourceManager.GetString("Socialie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string subscribe {
            get {
                return ResourceManager.GetString("subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Project Flame, CityU Wants a Better World..
        /// </summary>
        internal static string supportpf {
            get {
                return ResourceManager.GetString("supportpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string unsubscribe {
            get {
                return ResourceManager.GetString("unsubscribe", resourceCulture);
            }
        }
    }
}
