// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ProjectFLAME {
	
	
	public partial class unsubscribe {
		
		protected System.Web.UI.HtmlControls.HtmlForm Form1;
		
		protected System.Web.UI.WebControls.Literal head1;
		
		protected System.Web.UI.WebControls.Literal p;
		
		protected System.Web.UI.WebControls.Literal small;
		
		protected System.Web.UI.WebControls.Button undo;
	}
}
